INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (1, 1);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (1, 2);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (1, 3);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (1, 4);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (1, 5);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (1, 6);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (1, 7);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (1, 8);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (1, 9);

INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (2, 1);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (2, 2);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (2, 3);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (2, 4);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (2, 5);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (2, 6);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (2, 7);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (2, 8);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (2, 9);

INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (3, 1);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (3, 2);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (3, 3);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (3, 4);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (3, 5);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (3, 6);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (3, 7);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (3, 8);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (3, 9);

INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (4, 1);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (4, 2);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (4, 3);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (4, 4);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (4, 5);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (4, 6);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (4, 7);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (4, 8);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (4, 9);

INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (5, 1);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (5, 2);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (5, 3);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (5, 4);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (5, 5);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (5, 6);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (5, 7);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (5, 8);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (5, 9);

INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (6, 1);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (6, 2);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (6, 3);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (6, 4);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (6, 5);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (6, 6);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (6, 7);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (6, 8);
INSERT INTO `appDeVagas`.`vacancies_benefits` (`vacancies_fk`, `benefits_fk`) VALUES (6, 9);
