
INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'FullStack', 'Desenvolvedor de api e telas', 'Desenvolvedor FullStack', 1500, 'Junior', 'CLT', 'Joinviile/SC', 1);
INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'FrontEnd', 'Desenvolver telas e consumir api','Desenvolvedor Front End React', 1500, 'Junior', 'CLT', 'Joinviile/SC', 1);
INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'BackEnd', 'Desenvolver Apis ', 'Desenvolvedor BackEnd Java', 1500, 'Junior', 'CLT', 'Joinville/SC', 1);

INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'FullStack', 'Desenvolvedor de api e telas', 'Desenvolvedor FullStack', 1500, 'Junior', 'CLT', 'Joinviile/SC', 2);
INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'FrontEnd', 'Desenvolver telas e consumir api','Desenvolvedor Front End React', 1500, 'Junior', 'CLT', 'Joinviile/SC', 2);
INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'BackEnd', 'Desenvolver Apis ', 'Desenvolvedor BackEnd Java', 1500, 'Junior', 'CLT', 'Joinville/SC', 2);

INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'FullStack', 'Desenvolvedor de api e telas', 'Desenvolvedor FullStack', 1500, 'Junior', 'CLT', 'Joinviile/SC', 3);
INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'FrontEnd', 'Desenvolver telas e consumir api','Desenvolvedor Front End React', 1500, 'Junior', 'CLT', 'Joinviile/SC',3);
INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'BackEnd', 'Desenvolver Apis ', 'Desenvolvedor BackEnd Java', 1500, 'Junior', 'CLT', 'Joinville/SC', 3);

INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'FullStack', 'Desenvolvedor de api e telas', 'Desenvolvedor FullStack', 1500, 'Junior', 'CLT', 'Joinviile/SC', 4);
INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'FrontEnd', 'Desenvolver telas e consumir api','Desenvolvedor Front End React', 1500, 'Junior', 'CLT', 'Joinviile/SC', 4);
INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'BackEnd', 'Desenvolver Apis ', 'Desenvolvedor BackEnd Java', 1500, 'Junior', 'CLT', 'Joinville/SC', 4);

INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'FullStack', 'Desenvolvedor de api e telas', 'Desenvolvedor FullStack', 1500, 'Junior', 'CLT', 'Joinviile/SC', 5);
INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'FrontEnd', 'Desenvolver telas e consumir api','Desenvolvedor Front End React', 1500, 'Junior', 'CLT', 'Joinviile/SC', 5);
INSERT INTO `appDeVagas`.`vacancies` (`active`, `category`, `job_description`, `job_title`, `salary_range`, `seniority`, `type_of_contract`, `vacancy_location`, `company_id`) VALUES (1, 'BackEnd', 'Desenvolver Apis ', 'Desenvolvedor BackEnd Java', 1500, 'Junior', 'CLT', 'Joinville/SC', 5);
